# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 05:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, default=datetime.datetime(2017, 9, 2, 5, 7, 43, 503899))),
                ('end', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
